= How to Generate a Document Template for Pandoc and the ODT Format

Pandoc provides the ability to generate ODT files using a template. However, there is little documentation available on this topic online, as it is a niche feature (developers who use Pandoc rarely generate documents for external use).

== Creating the Reference Style Template

You need to create a reference style template. This step is mandatory for Pandoc to properly handle the formatting.

Run the following command:

```
make prepare
```

This command creates a `frame.fodt` document in the current directory. If a previous `frame.fodt` file already exists, it is backed up as `frame_old.fodt`.

== Creating the Document Template

Next, open the `frame.fodt` file in LibreOffice and edit it.

Make basic modifications and run tests with the `test.asc` file to validate the rendering of the styles.

To generate the result document, run:
+
```
make test_style
```

Check the result in the `test.fodt` file and make adjustments to `frame.fodt` until the rendered document matches your company’s template, both in terms of styles and cover pages.

You can also review the generated PDF and DOCX versions for validation.

NOTE: This command does not render the final template. You must generate the template (next step) to fully test your document.

== Injecting Templating Tags into the Document

The file supports a variety of templating tags. Most of these tags are wrapped in double curly braces, such as `{{author}}`.

The available tags are:

* `{{title}}`: Displays the document's title.
* `{{subtitle}}`: Displays the document's subtitle, if it exists.
* `{{revision}}`: Displays the document's revision/version.
* `{{date}}`: Displays the document's date (from the Asciidoctor file metadata or the file's modification date).
* `{{author}}`: The document's author (First Name and Last Name).
* `{{email}}`: The author's email address (if provided).
* `{{authorfirstname}}`: The author's first name.
* `{{authorsurname}}`: The author's last name.
* `{{authorinitials}}`: The author's initials.
* `{{reviewername}}`: The reviewer's name (First Name and Last Name).
* `{{reviewertitle}}`: The reviewer's title (e.g., "Infrastructure Manager").
* `{{approvername}}`: The approver's name (First Name and Last Name).
* `{{approvertitle}}`: The approver's title.
* `{{startrev}}` and `{{endrev}}`: Define the beginning and end of the section that repeats in the template to include revision history. These tags should surround all fields related to revisions. Typically, they are found in a table, with `{{startrev}}` on the first row and `{{endrev}}` on the second row.
* `{{revision}}`: This macro cannot be used alone but includes the following components:
  ** `{{revision.version}}`: The revision version number.
  ** `{{revision.author}}`: The initials of the revision's author.
  ** `{{revision.date}}`: The date of the revision.
  ** `{{revision.comment}}`: A description of the changes made in this revision.
* `{{startdoc}}`: Indicates where the main document content should be injected. This marks the beginning of the document's body within the template.
* `{{enddoc}}`: Marks the end of the body content. Everything after this point is preserved and considered part of the template.


The following tags are natively generated by Asciidoctor:

* `$title$`: The document's title (handled by Asciidoctor).
* `$subtitle$`: The document's subtitle (handled by Asciidoctor).
* `$author$`: The document's author, including their email address (handled by Asciidoctor).
* `$date$`: The document's date (handled by Asciidoctor).

== Styling Tables

By default, tables do not have borders or formatting. You can define a reference table named `ReferenceTable`, and its border, padding, and color attributes will be copied to all other tables in the document, except those whose names start with `__`.

IMPORTANT: The reference table must be present somewhere in the document (its size does not matter). It can be placed in a hidden area on the first page. The `reference.fodt` file includes an example of this table.

NOTE: This table formatting system will be simplified once LibreOffice or Pandoc natively supports table formatting.

== Preparing the Template

Run the following command:
+
```
make generate_template
```

This command prepares the `style.odt` and `template.fodt` files, which are used to generate the final documents.

== Testing the Template

You can now test the generated template.

Run the following command:
+
```
make test_template
```

All output documents will be generated in the current directory using the `test.asc` file.

If your document is correctly formatted, the generated files will respect the styles and formatting defined in the `frame.fodt` template.
